merge_base_with = "origin/master"

[[linter]]
code = 'FLAKE8'
include_patterns = ['**/*.py', '**/*.py.test']
command = [
    'python3',
    'tools/linter/adapters/flake8_linter.py',
    '--',
    '@{{PATHSFILE}}'
]


[[linter]]
code = 'MYPY'
include_patterns = ['**/*.py', '**/*.py.test']
exclude_patterns = ['tools/**', 'conftest.py']
command = [
    'python3',
    'tools/linter/adapters/mypy_linter.py',
    '--config=mypy.ini',
    '--',
    '@{{PATHSFILE}}'
]

[[linter]]
code = 'UFMT'
include_patterns = ['**/*.py', '**/*.pyi', '**/*.py.test']
command = [
    'python3',
    'tools/linter/adapters/ufmt_linter.py',
    '--',
    '@{{PATHSFILE}}'
]
is_formatter = true

[[linter]]
code = 'LINTRUNNER_VERSION'
include_patterns = ['**']
command = [
    'python3',
    'tools/linter/adapters/lintrunner_version_linter.py'
]
